apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hakoniwa.fullname" . }}
  labels:
    {{- include "hakoniwa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $jwtSecret := "" }}
  {{- if .Values.config.jwtSecret }}
    {{- $jwtSecret = .Values.config.jwtSecret }}
  {{- else }}
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "hakoniwa.fullname" .)) | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    {{- if (hasKey $secretData "jwt-secret") }}
      {{- $jwtSecret = (get $secretData "jwt-secret") | b64dec }}
    {{- else }}
      {{- $jwtSecret = randAlphaNum 32 }}
    {{- end }}
  {{- end }}
  jwt-secret: {{ $jwtSecret | b64enc | quote }}
  {{- if .Values.config.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.config.oidc.clientSecret | b64enc | quote }}
  {{- end }}
