apiVersion: v1
kind: Service
metadata:
  name: {{ include "hakoniwa.fullname" . }}
  labels:
    {{- include "hakoniwa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hakoniwa.selectorLabels" . | nindent 4 }}
