apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakoniwa
  labels:
    app.kubernetes.io/name: hakoniwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hakoniwa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hakoniwa
    spec:
      serviceAccountName: hakoniwa-sa
      containers:
        - name: hakoniwa
          image: docker.io/aplulu/hakoniwa:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
