apiVersion: v1
kind: Service
metadata:
  name: hakoniwa-service
  labels:
    app.kubernetes.io/name: hakoniwa
spec:
  selector:
    app.kubernetes.io/name: hakoniwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
