apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hakoniwa.fullname" . }}-pod-template
  labels:
    {{- include "hakoniwa.labels" . | nindent 4 }}
data:
  pod_template.yaml: |
{{- .Values.podTemplate.content | nindent 4 }}
